install: main.py ../lib/gps_area.py ../data/durham.coords ../data/nc.coords ../data/usa.coords
	ampy --port /dev/ttyUSB0 put main.py
	ampy --port /dev/ttyUSB0 put ../lib/gps_area.py
	ampy --port /dev/ttyUSB0 put ../data/durham.coords
	ampy --port /dev/ttyUSB0 put ../data/nc.coords
	ampy --port /dev/ttyUSB0 put ../data/usa.coords
