# Copy to $HOME/.config/iss-tracker.yml and set the values below
---
name: TrackerName
hue:
  host: http://<HUB_BRIDGE_HOST>
  token: 0xdeadbeef
  lights:
    - MyColorLight1
    - MyColorLight2
blynk:
  token: 0xabcd123ef
